Name:           perl-Path-Class
Version:        0.35
Release:        2%{?dist}
Summary:        Cross-platform path specification manipulation
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Path-Class/
Source0:        http://www.cpan.org/authors/id/K/KW/KWILLIAMS/Path-Class-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Module::Build) >= 0.3601
BuildRequires:  perl(parent)
BuildRequires:  perl(Perl::OSType)
BuildRequires:  perl(Test::More)
Requires:       perl(parent)
Requires:       perl(Perl::OSType)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Path::Class is a module for manipulation of file and directory
specifications (strings describing their locations, like
'/home/ken/foo.txt' or 'C:\Windows\Foo.txt') in a cross-platform manner. It
supports pretty much every platform Perl runs on, including Unix, Windows,
Mac, VMS, Epoc, Cygwin, OS/2, and NetWare.

%prep
%setup -q -n Path-Class-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes cpanfile dist.ini LICENSE README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 0.35-2
- ajout de la version minimum 0.3601 pour Module::Build

* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 0.35-1
- Specfile autogenerated by cpanspec 1.78.
