Name:           perl-Type-Tiny
Version:        1.000005
Release:        2%{?dist}
Summary:        Tiny, yet Moo(se)-compatible type constraint
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Type-Tiny/
Source0:        http://www.cpan.org/authors/id/T/TO/TOBYINK/Type-Tiny-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.006001
BuildRequires:  perl(Devel::LexAlias) >= 0.05
BuildRequires:  perl(Devel::StackTrace)
BuildRequires:  perl(Exporter::Tiny) >= 0.026
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Sub::Name)
BuildRequires:  perl(Test::More) >= 0.96
BuildRequires:  perl(Type::Tie)
BuildRequires:  perl(Type::Tiny::XS) >= 0.010
Requires:       perl(Devel::LexAlias) >= 0.05
Requires:       perl(Devel::StackTrace)
Requires:       perl(Exporter::Tiny) >= 0.026
Requires:       perl(Sub::Name)
Requires:       perl(Type::Tie)
Requires:       perl(Type::Tiny::XS) >= 0.010
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
Provides:       perl(Type::Library)

%description
Type::Tiny is a tiny class for creating Moose-like type constraint objects
which are compatible with Moo, Moose and Mouse.

%prep
%setup -q -n Type-Tiny-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes COPYRIGHT CREDITS dist.ini doap.ttl LICENSE META.json NEWS README TODO
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 1.000005-2
- Ajout de Provides:       perl(Type::Library)

* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 1.000005-1
- Specfile autogenerated by cpanspec 1.78.
