Name:           perl-CGI
Version:        4.13
Release:        4%{?dist}
Summary:        Handle Common Gateway Interface requests and responses
License:        CHECK(Distributable)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/CGI/
Source0:        http://www.cpan.org/authors/id/L/LE/LEEJO/CGI-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.008001
BuildRequires:  perl(Config)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(HTML::Entities) >= 3.69
BuildRequires:  perl(parent) >= 0.225
BuildRequires:  perl(Test::Deep)
BuildRequires:  perl(Test::Warn)
BuildRequires:  perl(Test::NoWarnings)
Requires:       perl(Config)
Requires:       perl(HTML::Entities) >= 3.69
Requires:       perl(parent) >= 0.225
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
CGI.pm is a stable, complete and mature solution for processing and
preparing HTTP requests and responses. Major features including processing
form submissions, file uploads, reading and writing cookies, query string
generation and manipulation, and processing and preparing HTTP headers.
Some HTML generation utilities are included as well.

%prep
%setup -q -n CGI-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes META.json README.md
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 4.13-4
- add BuildRequires:  perl(Test::Warn)
- add BuildRequires:  perl(Test::NoWarnings)

* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 4.13-3
- BuildRequires, pas Requires

* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 4.13-2
- add Requires:       perl(Test::Deep)

* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 4.13-1
- Specfile autogenerated by cpanspec 1.78.
