Name:           perl-Config-INI-Reader-Ordered
Version:        0.011
Release:        1%{?dist}
Summary:        .ini-file parser that returns sections in order
License:        CHECK(Distributable)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Config-INI-Reader-Ordered/
Source0:        http://www.cpan.org/authors/id/H/HD/HDP/Config-INI-Reader-Ordered-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Config::INI::Reader)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::More)
Requires:       perl(Config::INI::Reader)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Config::INI::Reader::Ordered is a subclass of Config::INI::Reader which
preserves section order. See Config::INI::Reader for all documentation; the
only difference is as presented in the "SYNOPSIS".

%prep
%setup -q -n Config-INI-Reader-Ordered-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 0.011-1
- Specfile autogenerated by cpanspec 1.78.
