Name:           perl-bareword-filehandles
Version:        0.003
Release:        2%{?dist}
Summary:        Disables bareword filehandles
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/bareword-filehandles/
Source0:        http://www.cpan.org/authors/id/I/IL/ILMARI/bareword-filehandles-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl >= 0:5.008001
BuildRequires:  perl(B::Hooks::OP::Check)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Lexical::SealRequireHints)
BuildRequires:  perl(Test::More) >= 0.88
BuildRequires:  perl(ExtUtils::Depends)
Requires:       perl(B::Hooks::OP::Check)
Requires:       perl(Lexical::SealRequireHints)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module lexically disables the use of bareword filehandles with builtin
functions, except for the special builitin filehandles STDIN, STDOUT,
STDERR, ARGV, ARGVOUT and DATA.

%prep
%setup -q -n bareword-filehandles-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE README weaver.ini
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/bareword*
%{_mandir}/man3/*

%changelog

* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 0.003-2
- Add BuildRequires:  perl(ExtUtils::Depends)

* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 0.003-1
- Specfile autogenerated by cpanspec 1.78.
