Name:           perl-multidimensional
Version:        0.011
Release:        2%{?dist}
Summary:        Disables multidimensional array emulation
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/multidimensional/
Source0:        http://www.cpan.org/authors/id/I/IL/ILMARI/multidimensional-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl >= 0:5.008
BuildRequires:  perl(B::Hooks::OP::Check) >= 0.19
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Lexical::SealRequireHints) >= 0.005
BuildRequires:  perl(Test::More) >= 0.88
BuildRequires:  perl(ExtUtils::Depends)
Requires:       perl(B::Hooks::OP::Check) >= 0.19
Requires:       perl(Lexical::SealRequireHints) >= 0.005
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Perl's multidimensional array emulation stems from the days before the
language had references, but these days it mostly serves to bite you when
you typo a hash slice by using the $ sigil instead of @.

%prep
%setup -q -n multidimensional-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE META.json README weaver.ini
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/multidimensional*
%{_mandir}/man3/*

%changelog
* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 0.011-2
- Add BuildRequires:  perl(ExtUtils::Depends)

* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 0.011-1
- Specfile autogenerated by cpanspec 1.78.
