Name:           perl-Test-File-Contents
Version:        0.21
Release:        1%{?dist}
Summary:        Test::File::Contents Perl module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Test-File-Contents/
Source0:        http://www.cpan.org/authors/id/D/DW/DWHEELER/Test-File-Contents-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.008003
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Test::Builder) >= 0.70
BuildRequires:  perl(Test::More) >= 0.70
BuildRequires:  perl(Test::Pod) >= 1.41
BuildRequires:  perl(Test::Pod::Coverage) >= 1.06
BuildRequires:  perl(Text::Diff) >= 0.35
Requires:       perl(Test::Builder) >= 0.70
Requires:       perl(Test::Pod) >= 1.41
Requires:       perl(Test::Pod::Coverage) >= 1.06
Requires:       perl(Text::Diff) >= 0.35
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
file_contents_eq         $file,     $contents,    $description;
file_contents_eq_or_diff $file,     $string,      $description;
file_contents_like       $file,     qr/contents/, $description;
file_md5_sum_is          $file,     $md5hash,     $description;

%prep
%setup -q -n Test-File-Contents-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes META.json README.md
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 0.21-1
- Specfile autogenerated by cpanspec 1.78.
