Name:           perl-JSON-PP
Version:        2.27300
Release:        2%{?dist}
Summary:        JSON::XS compatible pure-Perl module
License:        CHECK(Distributable)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/JSON-PP/
Source0:        http://www.cpan.org/authors/id/M/MA/MAKAMAKA/JSON-PP-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::More)
Requires:       perl(Test::More)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module is JSON::XS compatible pure Perl module. (Perl 5.8 or later is
recommended)

%prep
%setup -q -n JSON-PP-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*
%doc %{_mandir}/man1/json_pp.1*
%{_bindir}/json_pp

%changelog
* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 2.27300-2
- Modification des %files

* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 2.27300-1
- Specfile autogenerated by cpanspec 1.78.
