%define perl_vendorlib %(eval "`%{__perl} -V:installvendorlib`"; echo $installvendorlib)

Name:           perl-libintl-perl
Version:        1.23
Release:        4%{?dist}
Summary:        libintl::perl Perl module
License:        CHECK(Distributable)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/libintl-perl/
Source0:        http://www.cpan.org/authors/id/G/GU/GUIDO/libintl-perl-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::ShareDir)
BuildRequires:  perl(version) >= 0.77
Requires:       perl(File::ShareDir)
Requires:       perl(version) >= 0.77
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
The package libintl-perl is an internationalization library for Perl that
aims to be compatible with the Uniforum message translations system as
implemented for example in GNU gettext.

%prep
%setup -q -n libintl-perl-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc ChangeLog COPYING.LESSER Credits FAQ META.json MYMETA.json MYMETA.yml NEWS README README-oldversions README.solaris README.win32 REFERENCES ReleaseNotes THANKS TODO
%{perl_vendorarch}/auto/*
%{perl_vendorlib}/Locale/
%{_mandir}/man3/*

%changelog
* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 1.23-4
- ajoute la deifnition de perl_vendorlib
- transforme %{perl_vendorarch}/Locale/* en %{perl_vendorlib}/Locale/

* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 1.23-3
- ajoute %{perl_vendorarch}/Locale/* à %files

* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 1.23-2
- supprime %{perl_vendorarch}/libintl* de %files

* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 1.23-1
- Specfile autogenerated by cpanspec 1.78.
