Name:           perl-WWW-Pastebin-PastebinCom-Create
Version:        1.003
Release:        1%{?dist}
Summary:        Paste on www.pastebin.com without API keys
License:        Artistic 2.0
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/WWW-Pastebin-PastebinCom-Create/
Source0:        http://www.cpan.org/authors/id/Z/ZO/ZOFFIX/WWW-Pastebin-PastebinCom-Create-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.006
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Moo) >= 1.004001
BuildRequires:  perl(Test::More)
BuildRequires:  perl(WWW::Mechanize) >= 1.73
Requires:       perl(Moo) >= 1.004001
Requires:       perl(WWW::Mechanize) >= 1.73
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module provides the means to paste on www.pastebin.com pastebin,
without the need for API keys. See the WARNING!!! section above.

%prep
%setup -q -n WWW-Pastebin-PastebinCom-Create-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes examples LICENSE META.json README xt
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 1.003-1
- Specfile autogenerated by cpanspec 1.78.
