Name:           perl-LWP-MediaTypes
Version:        6.02
Release:        3%{?dist}
Summary:        Guess media type for a file or a URL
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/LWP-MediaTypes/
Source0:        http://www.cpan.org/authors/id/G/GA/GAAS/LWP-MediaTypes-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.006002
BuildRequires:  perl(ExtUtils::MakeMaker)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module provides functions for handling media (also known as MIME)
types and encodings. The mapping from file extensions to media types is
defined by the media.types file. If the ~/.media.types file exists it is
used instead. For backwards compatibility we will also look for
~/.mime.types.

%prep
%setup -q -n LWP-MediaTypes-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=site
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

#suppression des documentations
find $RPM_BUILD_ROOT -type f -name "*.3pm" -exec rm -f {} \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_sitelib}/*
#%{_mandir}/man3/*

%changelog
* Fri Jul 29 2016 Jean-Michel REY <vreb87@gmail.com> 6.02-3
- passe dans le dossier perl/site

* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 6.02-2
- supprime les fichiers de manuel, en conflit avec perl-libwww-perl-5.833-2.el6.noarch

* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 6.02-1
- Specfile autogenerated by cpanspec 1.78.
