Name:           perl-Proc-InvokeEditor
Version:        1.07
Release:        2%{?dist}
Summary:        Perl extension for starting a text editor
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Proc-InvokeEditor/
Source0:        http://www.cpan.org/authors/id/M/MS/MSTEVENS/Proc-InvokeEditor-%{version}.tar.gz
Patch0:         Proc-InvokeEditor-1.07-test.patch
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Carp::Assert) >= 0.11
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(IPC::Cmd)
BuildRequires:  perl(Test::More) >= 0.08
Requires:       perl(Carp::Assert) >= 0.11
Requires:       perl(IPC::Cmd)
Requires:       perl(Test::More) >= 0.08
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module provides the ability to supply some text to an external text
editor, have it edited by the user, and retrieve the results.

%prep
%setup -q -n Proc-InvokeEditor-%{version}
%patch0 -p1

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes LICENSE README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 1.07-2
- supprime un test interactif

* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 1.07-1
- Specfile autogenerated by cpanspec 1.78.
