Name:           perl-DBD-mysql
Version:        4.029
Release:        3%{?dist}
Summary:        MySQL driver for the Perl5 Database Interface (DBI)
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/DBD-mysql/
Source0:        http://www.cpan.org/authors/id/C/CA/CAPTTOFU/DBD-mysql-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl >= 0:5.008001
BuildRequires:  perl(DBI) >= 1.08
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::Deep)
BuildRequires:  perl(Test::More)
BuildRequires:  mysql, mysql-devel, zlib-devel
Requires:       perl(DBI) >= 1.08
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
DBD::mysql is the Perl5 Database Interface driver for the MySQL database.
In other words: DBD::mysql is an interface between the Perl programming
language and the MySQL programming API that comes with the MySQL relational
database management system. Most functions provided by this programming API
are supported. Some rarely used functions are missing, mainly because no-
one ever requested them. :-)

%prep
%setup -q -n DBD-mysql-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS" --testuser=root
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
# Full test coverage requires a live MySQL database
#make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc ChangeLog Makefile.PL.embedded myld TODO
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/DBD*
%{perl_vendorarch}/Bundle/DBD*
%{_mandir}/man3/*

%changelog
* Sun Mar 01 2015 Jean-Michel REY <vreb87@gmail.com> 4.029-3
- ajoute %{perl_vendorarch}/Bundle/DBD*

* Sun Mar 01 2015 Jean-Michel REY <vreb87@gmail.com> 4.029-2
- désactive les tests, qui ont besoin d'une database live

* Sun Mar 01 2015 Jean-Michel REY <vreb87@gmail.com> 4.029-1
- Specfile autogenerated by cpanspec 1.78.
