Name:           perl-HTML-Form
Version:        6.03
Release:        4%{?dist}
Summary:        Class that represents an HTML form element
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/HTML-Form/
Source0:        http://www.cpan.org/authors/id/G/GA/GAAS/HTML-Form-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.008001
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(HTML::TokeParser)
BuildRequires:  perl(HTTP::Request) >= 6
BuildRequires:  perl(HTTP::Request::Common) >= 6.03
BuildRequires:  perl(URI) >= 1.10
BuildRequires:  perl(Test::More)
Requires:       perl(HTML::TokeParser)
Requires:       perl(HTTP::Request) >= 6
Requires:       perl(HTTP::Request::Common) >= 6.03
Requires:       perl(URI) >= 1.10
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Objects of the HTML::Form class represents a single HTML <form> ... </form>
instance. A form consists of a sequence of inputs that usually have names,
and which can take on various values. The state of a form can be tweaked
and it can then be asked to provide HTTP::Request objects that can be
passed to the request() method of LWP::UserAgent.

%prep
%setup -q -n HTML-Form-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=site
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

#suppression des documentations
find $RPM_BUILD_ROOT -type f -name "*.3pm" -exec rm -f {} \;


%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_sitelib}/*

%changelog
* Fri Jul 29 2016 Jean-Michel REY <vreb87@gmail.com> 6.03-4
- passe dans le dossier perl/site

* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 6.03-3
- supprime les fichiers de manuel, en conflit avec perl-libwww-perl-5.833-2.el6.noarch

* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 6.03-2
-add BuildRequires:  perl(Test::More)

* Sat Feb 28 2015 Jean-Michel REY <vreb87@gmail.com> 6.03-1
- Specfile autogenerated by cpanspec 1.78.
